/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_nengo_util_impl_GPUThread */

#ifndef _Included_ca_nengo_util_impl_GPUThread
#define _Included_ca_nengo_util_impl_GPUThread
#ifdef __cplusplus
extern "C" {
#endif
#undef ca_nengo_util_impl_GPUThread_MIN_PRIORITY
#define ca_nengo_util_impl_GPUThread_MIN_PRIORITY 1L
#undef ca_nengo_util_impl_GPUThread_NORM_PRIORITY
#define ca_nengo_util_impl_GPUThread_NORM_PRIORITY 5L
#undef ca_nengo_util_impl_GPUThread_MAX_PRIORITY
#define ca_nengo_util_impl_GPUThread_MAX_PRIORITY 10L
/*
 * Class:     ca_nengo_util_impl_GPUThread
 * Method:    nativeSetupRun
 * Signature: ([[[[F[[F[[[F[[[[F[[FZ[[I)V
 */
JNIEXPORT void JNICALL Java_ca_nengo_util_impl_GPUThread_nativeSetupRun
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jintArray, jfloat);

/*
 * Class:     ca_nengo_util_impl_GPUThread
 * Method:    nativeStep
 * Signature: ([[[F[[[F[[FFF)V
 */
JNIEXPORT void JNICALL Java_ca_nengo_util_impl_GPUThread_nativeStep
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jobjectArray, jfloat, jfloat);

/*
 * Class:     ca_nengo_util_impl_GPUThread
 * Method:    nativeKill
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_nengo_util_impl_GPUThread_nativeKill
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
