class BasicOrigin: pass
class NetworkImpl: pass
class EnsembleTermination: pass
class PreciseSpikeOutputImpl: pass
class SpikeOutputImpl: pass
class RealOutputImpl: pass
class PlasticEnsembleTermination: pass
class NoiseFactory: pass
class FunctionInput: pass
class PlasticEnsembleImpl: pass
