#!/usr/bin/env bash

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
java -Xms100m -Xmx800m -cp .:nengo-BUILDNUMBER.jar:LIBS -Djava.library.path=NengoGPU:NengoUtilsGPU ca.nengo.ui.NengoLauncher
